source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CJL9567/SJTYLogManagerSpecs.git'
use_frameworks!

platform :ios, '10.0'

target 'SJTYBleManager_Example' do
  pod 'SJTYBleManager', :path => '../'

  target 'SJTYBleManager_Tests' do
    inherit! :search_paths

    
  end
end
